project:
  type: website
  output-dir: docs

website:
  title: "Jacob Lawrence"
  favicon: infinity.svg
  navbar:
    tools:
      - icon: envelope
        href: mailto:jlqbx@missouri.edu
    search: false
    left:
      - research.qmd
      - teaching.qmd
      - coursework.qmd
      - projects.qmd

format:
  html:
    respect-user-color-scheme: true
    theme:
      light: [cosmo]
      dark: [cosmo, theme-dark.scss]
    css: styles.css
    toc: true




