project:
  type: website
  output-dir: docs

website:
  title: "Jacob Lawrence"
  navbar:
    search: false
    left:
      - research.qmd
      - teaching.qmd
      - coursework.qmd
      - projects.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



