project:
  type: website
  output-dir: docs

website:
  title: "Jacob Lawrence"
  favicon: files/infinity.svg
  bread-crumbs: true
  google-analytics: G-1JBEBWWGE2
  navbar:
    tools:
      - icon: github
        href: https://github.com/jtylawrence
      - icon: envelope
        href: mailto:jlqbx@missouri.edu
    search: false
    left:
      - text: Home
        href: index.qmd
      - text: Research
        href: Research/index.qmd
      - text: Teaching
        href: Teaching/index.qmd
      - text: Coursework
        href: Coursework/index.qmd
      - text: Projects
        href: Projects/index.qmd

format:
  html:
    respect-user-color-scheme: true
    theme:
      light: [cosmo]
      dark: [cosmo, files/theme-dark.scss]
    css: styles.css
    toc: true